// https://www.randomlists.com/random-addresses?qty=10
const streetCityNames = ["EAST COOPER","GREENROSE","GREENVIEW","SAN PABLO","DEL MONTE","BUCKINGHAM","BAKER","PRINCESS","FAIRWAY","ACACIA","CANTERBURY","RANDALL MILL","SOMERSET","ORANGE","IROQUOIS","SCHOOL","ALDERWOOD","GLEN ELLYN","LOCKPORT","FAIRFIELD","PHOENIX","HOPEWELL"];
const citySuffixes = ["CITY","TOWN","SVILLE","PARK"];
// https://pe.usps.com/text/pub28/28apc_002.htm
const streetSuffixes = ["AVENUE","BLVD","DR","EXPY","FALLS","HEIGHTS","LANE","PARK","PKWY","PLAZA","RIDGE","RD","SPRINGS","SQUARE","WAY"];
// http://officeipsum.com/index.php
const descriptions = [
    "Consequuntur elit or aspernatur quo. Ea laborum consequuntur beatae, yet consequat. Commodi. Nostrum. Nulla aliquip and magnam duis minima. Omnis commodi. Inventore. Occaecat sed. Si numquam yet tempor. Ea veniam, nihil but incididunt do for commodo yet quam. Sit. Nisi cillum and lorem. Qui. Dolores voluptatem nisi but tempora yet commodi. Esse. Si minim for sunt. Ratione sit or reprehenderit. Amet magnam ratione, molestiae. Lorem illo, rem minim pariatur nor aperiam error. Lorem pariatur eaque but deserunt but anim. Aute culpa for adipisicing lorem exercitationem so quasi so quae. Sint. Nostrud beatae.",

    "Pariatur iste and exercitation nostrud. Laborum. Odit consectetur cupidatat and minim culpa or voluptatem. Nulla in in and rem, aperiam nor nesciunt. Illum suscipit nor dolorem quo nequeporro. Eiusmod aliquam exercitation for duis but eius, but occaecat. Beatae qui for veritatis. Dolorem occaecat aliqua laboriosam. Fugiat beatae and explicabo. Illo. Voluptas. Minima eos, so commodo yet ad and magni, quo. Modi. Et ex ipsum mollit eos. Esse nemo, and sequi voluptatem.",

    "Nostrud explicabo velitesse natus, for consequuntur magna but magna. Unde magni eum exercitationem but velitesse so aliquip. Nemo molestiae inventore but mollit, sed for nihil. Culpa autem elit or omnis laudantium. Inventore voluptatem natus modi. Quia. Reprehenderit aliquam magnam. Exercitationem perspiciatis. Quam. Iure aspernatur or qui dicta. Quam minima duis laboris so magni. Voluptate. Suscipit. Ratione deserunt and id. Laboriosam aliquid but ipsam, quisquam accusantium and nequeporro. Ipsum. Fugit vitae but fugit. Ab inventore mollit nor magna molestiae. Minima duis for autem dicta.",

    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget nunc lobortis mattis aliquam. Venenatis lectus magna fringilla urna. Adipiscing vitae proin sagittis nisl rhoncus. Sit amet consectetur adipiscing elit duis tristique. At tellus at urna condimentum mattis pellentesque id nibh tortor. Massa tempor nec feugiat nisl. Mi eget mauris pharetra et ultrices. Egestas tellus rutrum tellus pellentesque eu. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Nulla aliquet enim tortor at auctor urna nunc. Porttitor lacus luctus accumsan tortor posuere. Condimentum id venenatis a condimentum. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Fermentum leo vel orci porta non pulvinar neque laoreet suspendisse. Eget duis at tellus at urna. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Magna eget est lorem ipsum dolor. At lectus urna duis convallis convallis tellus id interdum velit. Sodales neque sodales ut etiam."
];
const campusSuffixes = ["CAMPUS", "COLLEGE", "ACADEMY"];
const campusImages = ["https://www.oxy.edu/sites/default/files/styles/banner_image/public/page/banner-images/our-campus_1440x800.jpg?itok=ytH_0u--","https://www.aclu.org/sites/default/files/field_image/web17-collegecampus-socialshare-1200x628.jpg","https://media.istockphoto.com/photos/aerial-over-north-carolina-central-university-in-the-spring-picture-id1323420737?b=1&k=20&m=1323420737&s=170667a&w=0&h=rYBFNoi7xqsO83MSJmrWeR2kLkD5S8zqAU9mV1mJNA8="]
// https://github.com/arineng/arincli/blob/master/lib
const lastNames = ["FOO","BAR","BAZ","SMITH","JOHNSON","WILLIAMS","JONES","DAVIS","MILLER","WILSON","MOORE","TAYLOR","ANDERSON","THOMAS","JACKSON","HARRIS","MARTIN","THOMPSON","GARCIA","MARTINEZ","ROBINSON","CLARK","RODRIGUEZ","LEWIS","LEE","WALKER","HALL","ALLEN","HERNANDEZ","KING","WRIGHT","LOPEZ","HILL","SCOTT","GREEN","ADAMS","BAKER","GONZALEZ","NELSON","CARTER","MITCHELL","PEREZ","ROBERTS","TURNER","PHILLIPS","CAMPBELL",'PARKER',"EVANS","EDWARDS","COLLINS"];
const firstNames = ["FOO","BAR","BAZ","JAMES","JOHN","ROBERT","MICHAEL","WILLIAM","DAVID","RICHARD","CHARLES","JOSEPH","THOMAS","CHRISTOPHER","DANIEL","PAUL","MARK","DONALD","GEORGE","KENNETH","STEVEN","EDWARD","BRIAN","ANGEL","NATHANIEL","RAFAEL","LESLIE","EDGAR","MILTON","RAUL","BEN","CHESTER","CECIL","DUANE","FRANKLIN","ANDRE","ELMER","BRAD","GABRIEL","HELEN","SANDRA","DONNA","CAROL","RUTH","SHARON","MICHELLE","LAURA","SARAH","KIMBERLY","DEBORAH","JESSICA","SHIRLEY","CYNTHIA","ANGELA","MELISSA","BRENDA","AMY","ANNA","REBECCA","VIRGINIA","KATHLEEN","SARA","ANNE","JACQUELINE","WANDA","BONNIE","JULIA","RUBY","LOIS","TINA","PHYLLIS","NORMA","PAULA","DIANA","ANNIE","LILLIAN","EMILY","ROBIN","PEGGY","CRYSTAL","GLADYS","RITA","DAWN","CONNIE","FLORENCE"];
const emailSuffixes = ["@gmail.com","@yahoo.com","@aol.com"]
const alphabet = "QWERTYUIOPASDFGHJKLZXCVBNM";

module.exports = {streetCityNames, citySuffixes, streetSuffixes, descriptions, campusSuffixes, campusImages, lastNames, firstNames, emailSuffixes, alphabet};
